[project]
name = "aiagent1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "openai>=2.11.0",
    "openai-agents>=0.6.3",
]
